MicroInternshipsApp/Models/OrganizationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MicroInternshipsApp.Models
{
    public class OrganizationModel
    {
        [Display(Name = "Organization Name")]
        [Required(ErrorMessage = "Please enter a name")]
        public string OrganizationName { get; set; }
        [Display(Name = "Organization Type")]
        [Required(ErrorMessage = "Is the organization for profit or non-profit")]
        public string OrganizationType { get; set; }
        [Display(Name = "Website")]
        public string OrganizationWebsite { get; set; }
    }
}

MicroInternshipsApp/Models/ProjectModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MicroInternshipsApp.Models
{
    public class ProjectModel
    {
        [Display(Name = "Title")]
        [Required(ErrorMessage = "Please enter a title")]
        public string Title { get; set; }
        [Display(Name = "Description")]
        [Required(ErrorMessage = "Please enter a description")]
        public string Description { get; set; }
        [Display(Name = "Topic")]
        public string Topic { get; set; }
    }
}

MicroInternshipsApp/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MicroInternshipsApp.Models
{
    public class UserModel
    {
        [Display(Name = "N-Number")]
        [Range(10000000, 99999999, ErrorMessage = "N-Number must be 8-digits long")]
        public int NNum { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Required Field")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Required Field")]
        public string LastName { get; set; }
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Required Field")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Required Field")]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "Password must be between 8 and 100 characters")]
        public string Password { get; set; }
        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "Required Field")]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "Password must be between 8 and 100 characters")]
        [Compare("Password", ErrorMessage = "Password does not match")]
        public string ConfirmPassword { get; set; }
    }
}

MicroInternshipsApp/Controllers/AdministratorController.cs
using DataLibrary.BusinessLogic;
using MicroInternshipsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MicroInternshipsApp.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator
        public ActionResult Index()
        {
            ViewBag.Message = "Administrator";

            return View();
        }
        public ActionResult ViewUsers()
        {
            ViewBag.Message = "User List";

            var data = UserProcessor.LoadUsers();
            List<UserModel> users = new List<UserModel>();

            foreach (var row in data)
            {
                users.Add(new UserModel
                {
                    NNum = row.NNum,
                    FirstName = row.FirstName,
                    LastName = row.LastName,
                    Email = row.Email
                });
            }

            return View(users);
        }
        public ActionResult ViewProjects()
        {
            ViewBag.Message = "Project List";

            var data = ProjectProcessor.LoadProjects();
            List<ProjectModel> projects = new List<ProjectModel>();

            foreach (var row in data)
            {
                projects.Add(new ProjectModel 
                {
                    Title = row.Title,
                    Description = row.Description,
                    Topic = row.Topic
                });
            }

            return View(projects);
        }
        public ActionResult ViewOrganization()
        {
            ViewBag.Message = "Organization List";

            var data = OrganizationProcessor.LoadOrganization();
            List<OrganizationModel> organizations = new List<OrganizationModel>();

            foreach (var row in data)
            {
                organizations.Add(new OrganizationModel 
                {
                    OrganizationName = row.OrganizationName,
                    OrganizationType = row.OrganizationType,
                    OrganizationWebsite = row.OrganizationWebsite
                });
            }

            return View(organizations);
        }
    }
}

MicroInternshipsApp/Controllers/CommunityController.cs
using MicroInternshipsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary;
using DataLibrary.BusinessLogic;

namespace MicroInternshipsApp.Controllers
{
    public class CommunityController : Controller
    {
        // GET: Community
        public ActionResult Index()
        {
            ViewBag.Message = "Community User";

            return View();
        }
        public ActionResult CreateProject()
        {
            ViewBag.Message = "Create Project";

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProject(ProjectModel model)
        {
            if (ModelState.IsValid)
            {
                int recordsCreated = ProjectProcessor.CreateProject(model.Title, model.Description, model.Topic);
                return RedirectToAction("Index");
            }

            return View();
        }
        public ActionResult NewOrganization()
        {
            ViewBag.Message = "Register Organization";

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewOrganization(OrganizationModel model)
        {
            if (ModelState.IsValid)
            {
                int recordsCreated = OrganizationProcessor.NewOrganization(model.OrganizationName,
                   model.OrganizationType, model.OrganizationWebsite);
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

MicroInternshipsApp/Controllers/HomeController.cs
using MicroInternshipsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary;
using DataLibrary.BusinessLogic;

namespace MicroInternshipsApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Register()
        {
            ViewBag.Message = "User Registration";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserModel model)
        {
            if (ModelState.IsValid)
            {
                int recordsCreated = UserProcessor.CreateUser(model.NNum, model.FirstName, 
                    model.LastName, model.Email);
                return RedirectToAction("Index");
            }

            return View();
        }

    }
}

MicroInternshipsApp/Views/Administrator/Index.cshtml
@{
    ViewBag.Title = "Reports";
}

<h2>Reports</h2>
<ul>
    <li>@Html.ActionLink("View Users", "ViewUsers", "Administrator")</li>
    <li>@Html.ActionLink("View Projects", "ViewProjects", "Administrator")</li>
    <li>@Html.ActionLink("View Organizations", "ViewOrganization", "Administrator")</li>
</ul>

MicroInternshipsApp/Views/Administrator/ViewOrganization.cshtml
@model IEnumerable<MicroInternshipsApp.Models.OrganizationModel>

@{
    ViewBag.Title = "Organization Report";
}

<h2>Organization Report</h2>

<p>
    @Html.ActionLink("Create New", "NewOrganization", "Community")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationWebsite)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizationName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizationType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizationWebsite)
        </td>
    </tr>
}

</table>

MicroInternshipsApp/Views/Administrator/ViewProjects.cshtml
@model IEnumerable<MicroInternshipsApp.Models.ProjectModel>

@{
    ViewBag.Title = "Project Report";
}

<h2>Project Report</h2>

<p>
    @Html.ActionLink("Create New", "RegisterProject", "Community")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Topic)
        </td>
    </tr>
}

</table>

MicroInternshipsApp/Views/Administrator/ViewUsers.cshtml
@model IEnumerable<MicroInternshipsApp.Models.UserModel>

@{
    ViewBag.Title = "User Report";
}

<h2>User Report</h2>

<p>
    @Html.ActionLink("Create New", "Register", "Home")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
    </tr>
}

</table>

MicroInternshipsApp/Views/Community/CreateProject.cshtml
@model MicroInternshipsApp.Models.ProjectModel

@{
    ViewBag.Title = "Create a Project";
}

<h2>Create a Project</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MicroInternshipsApp/Views/Community/Index.cshtml
@{
    ViewBag.Title = "Community User";
}

<h2>Community User</h2>
<ul>
    <li>@Html.ActionLink("Create Project", "CreateProject", "Community")</li>
    <li>@Html.ActionLink("Register Organization", "NewOrganization", "Community")</li>
</ul>

MicroInternshipsApp/Views/Community/NewOrganization.cshtml
@model MicroInternshipsApp.Models.OrganizationModel

@{
    ViewBag.Title = "Register Organization";
}

<h2>Register Organization</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrganizationModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationWebsite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationWebsite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationWebsite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MicroInternshipsApp/Views/Community/NewProject.cshtml
@model MicroInternshipsApp.Models.ProjectModel

@{
    ViewBag.Title = "CreateProject";
}

<h2>CreateProject</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MicroInternshipsApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Micro-Internship Portal</h1>
    <p class="lead">Currently under construction!</p>
    <p><a href="https://github.com/joshua-aquino/MicroInternships" class="btn btn-primary btn-lg">Github &raquo;</a></p>
</div>

MicroInternshipsApp/Views/Home/Register.cshtml
@model MicroInternshipsApp.Models.UserModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MicroInternshipsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Application</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a href="https://www.unf.edu">
                    <img src="https://www.unf.edu/uploadedImages/images/logos/UNF_Logo.gif" alt="UNF" border="0">
                </a>
                <a href="https://www.unf.edu/ccbl">
                    <img src="https://www.unf.edu/uploadedImages/images/logos/ccbl.gif" alt="Center for Community-Based Learning" border="0">
                </a>
            </div>
        </nav>
    </header>
    <div class="container" id="guide">
        <div class="row">
            <div class="col-sm-2">@Html.ActionLink("Home", "Index", "Home")</div>
            <div class="col-sm-2">@Html.ActionLink("Administrator", "Index", "Administrator")</div>
            <div class="col-sm-2">@Html.ActionLink("Community", "Index", "Community")</div>
            <div class="col-sm-2">@Html.ActionLink("Register", "Register", "Home")</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>